---
title: "Heatmap [LOD & Herit] (no adjustment)"
author: "Belinda Cornes"
date: "19/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("ggdendro")
library("reshape2")
library("grid")
library(ggplot2)
library(dplyr)
library(ggnewscale)
library(RColorBrewer)
library(qtl2)

source("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/heh/code/reconst_utils.R")

markers = read.delim("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/heh/data/marker_grid_0.02cM_plus.txt", stringsAsFactors = F)
markers[,2] = factor(markers[,2], levels = c(1:19, "X"))

```


### Phylum
```{r phylum, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "Phylum"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

  ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.53, width = 0.2, height = 0.79))
  
  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }
   
```

### Class
```{r class, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "Class"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

  ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.53, width = 0.2, height = 0.79))

  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }
   
```

### Order
```{r order, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "Order"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

   ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.53, width = 0.2, height = 0.79))

  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }
   
```

### Family
```{r family, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "Family"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

  ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.53, width = 0.2, height = 0.79))

  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }
   
```

### Genus
```{r genus, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "Genus"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

 ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.53, width = 0.2, height = 0.79))

  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }
   
```

### OTU
```{r otu, fig.height = 6, fig.width = 9.5, fig.align = "center"}

level = "OTU"

load(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/results/qtl.viewer/run14/results/",level,"_ready.Rdata"))

print("stool")
lod.sens.all.s <- as.data.frame(qtl.genus.sq.s)
print(ncol(lod.sens.all.s))

print("cecum")
lod.sens.all.c <- as.data.frame(qtl.genus.sq.c)
print(ncol(lod.sens.all.c))

files <- grep("lod.sens",names(.GlobalEnv),value=TRUE)
for(df in 1:length(files)){
   
#  pdf(paste0("/Users/corneb/Documents/MyJax/CS/Projects/Bubier/Figures/corneb/output/qtlmapping.heatmap_cluster_",files[df],"_",level,"_run14_max-lod-8.pdf"), width = 14, height = 7)

  x <- get(files[df])
  x[is.na(x)] <- 0
  x.matrix <- as.matrix(t(x))
  x.dendro <- as.dendrogram(hclust(d = dist(x = x.matrix)))

  # Create dendro
  dendro.plot <- ggdendrogram(data = x.dendro, rotate = TRUE) + 
                 theme(axis.text.y = element_blank(), 
                       axis.text.x = element_blank())

  xt <- as.data.frame(t(x))
  xt$entity <- rownames(xt)
  st <- sapply(strsplit(files[df],'.', fixed = TRUE),function(x) x[4])
  if(st == 'c'){
      herit.df <- as.data.frame(herit.c)
      origin = "cecum"
  }else{
      herit.df <- as.data.frame(herit.s)
      origin = "stool"
  }
  herit.df$entity = rownames(herit.df)
  xth <- merge(herit.df, xt, by=c("entity"), all.y=T)
  
  xh.long <- melt(xth, id=c("entity"))
  xh.long$chr <- sapply(strsplit(as.character(xh.long$variable),'_', fixed = TRUE),function(x) x[1])
  xh.long[xh.long$chr == xh.long$variable,]$chr <- "herit"
  xh.long$chr <- factor(xh.long$chr, levels=c("herit",1:19,"X"))

  min = min(xh.long$value)
  max = max(xh.long$value)

  ColorRamp   <- brewer.pal(n=length(3:max), "YlOrRd")
  #colours <- rbind(data.frame(ColorRamp=c("white","white")), as.data.frame(ColorRamp))

  xh.order <- order.dendrogram(x.dendro)
  xh.long$entity <- factor(x = xh.long$entity, 
                           levels = xth$entity[xh.order], 
                           ordered = TRUE)
  xh.long$category <- ifelse(xh.long$chr == "herit", "heritability", "qtl")

  heatmap.plot.2 <-ggplot() +
                   geom_raster(data = xh.long[xh.long$category == "heritability",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradient(low = "lightblue", high = "darkblue", name = "heritability") +
                   new_scale_fill() +
                   geom_raster(data = xh.long[xh.long$category == "qtl",], aes(x = variable, y = entity, fill = value)) +
                   scale_fill_gradientn(limits = c(3,max),colours=ColorRamp, name = "LOD score",na.value = 'white') +
                   facet_grid(~ chr,scales = "free", space = "free_y") +
                   ggtitle(paste0("QTL Mapping & Heritability - ", level,":", origin)) +
                   theme(axis.text.x = element_blank(),
                         axis.text.y = element_text(size = 5),
                         axis.ticks.x = element_blank(),
                         plot.title = element_text(hjust = 0.5),
                         legend.position = "bottom")

  grid.newpage()
  print(heatmap.plot.2, vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
  print(dendro.plot, vp = viewport(x = 0.90, y = 0.52, width = 0.2, height = 0.90))
  
  #dev.off()
  
  print(find_peaks(x ,map, threshold = 5))
  
 }

```